[package]
authors = ["adoo <Adoo@outlook.com>"]
edition = "2021"
name = "gpu"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guillotiere = "0.6.0"
log = "0.4.8"
lyon_tessellation = "0.17.10"
painter = {path = "../painter"}
zerocopy = "0.3"
unicode-linebreak = "0.1.2"
rustybuzz="0.4.0"
ttf-parser="0.14.0"

png = {version = "0.16.7"}
raw-window-handle = {version = "0.3.3", optional = true}
wgpu = {version = "0.6.0", optional = true}

[dev-dependencies]
env_logger = "0.7.1"
futures = "0.3.5"
unit_test = {path = "../unit_test"}
winit = "0.24.0"

[features]
wgpu_gl = ["wgpu", "raw-window-handle"]
