[workspace]
edition = "2021"
members = [
  "core",
  "gpu",
  "painter",
  "unit_test",
  "widget_derive",
  "algo",
  "text",
]
resolver = "2"

[profile.bench]
debug = true

[profile.release]
debug = true
