[package]
name = "core"
version = "0.1.0"
authors = ["adoo <Adoo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
herald = {path= "../../herald"}
slab_tree = "0.3"
rxrust = {path="../../rx_rs"}