[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/ribir"
version.workspace = true

[dependencies]
ribir_core = {path = "../core", version = "0.0.0"}
ribir_gpu = {path = "../gpu", version = "0.0.0"}
ribir_widgets = {path = "../widgets", version = "0.0.0"}
winit.workspace = true

[dev-dependencies]
env_logger.workspace = true
image.workspace = true
ribir_material = {path = "../themes/material", version = "0.0.0"}

[features]
default = ["wgpu"]
png = ["ribir_core/png"]
wgpu = ["ribir_gpu/wgpu"]
