[package]
authors = ["wjian23 <w_jian23@163.com>"]
edition = "2021"
name = "animation"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rxrust = "1.0.0-alpha.2"
ribir = {path = "../core"}
lyon = "0.17.10"